
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app        # mount project
      - ./questions:/questions
      - ./backend/FIREBASE_CRED.json:/FIREBASE_CRED.json
  code_sandbox:
    build: 
      context: ./code_sandbox
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  ai_workspace:
    build: 
      context: ./ai_workspace
      dockerfile: Dockerfile.dev
    env_file:
      - ./ai_workspace/.env
    ports:
      - 8001:8001
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app        # mount project
      - /app/node_modules      # do NOT overwrite node_modules
    environment:
    - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env
    tty: true
    stdin_open: true



