name: AI Workspace CI

# Only triggers if there is a  change
on:
  push:
    paths: 
      - 'ai_workspace/**'
      - '.github/workflows/ai_workspace_build.yml'
    branches: ["main", "dev"]
    
  pull_request:
    paths: 
      - 'ai_workspace/**'
      - '.github/workflows/ai_workspace_build.yml'
    branches: ["dev", "main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13]

    env:
      MODE: "dev"
      # TODO: is to add the actual ai env keys on here
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      TAVILY_API_KEY: ${{secrets.TAVILY_API_KEY}}

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}


      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

        working-directory: ./ai_workspace

      - name: Install dependencies
        run: poetry install
        working-directory: ./ai_workspace

      - name: Run Test
        run: |
          poetry run python -m pytest -s --log-cli-level=INFO
        working-directory: ./ai_workspace
